version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring_boot
    restart: always
    build: ./src
    working_dir: .
    volumes:
      - ./app:/app
      - ~/.m2:/root/.m2
    expose:
      - "8080"
    command: mvn clean spring-boot:run
